### ISSUE TITLE
FileUploadSelector doesn't work on Chrome (after update 78->79)

### ISSUE THREAD

**Issue by radekcz** [exxcellent/echopoint#2]
After update Chrome on version 79 FileUploadSelector has stopped working (on 78 is working fine).

This component starts communication with server:

    ?sid=echopoint.tucana.UploadProgressService&i=C.3109&x=3clunmk42z0ozk

but it'll get response:

    {r:0,cl:0,pc:0,tr:0,tl:0,s:'failed',m:''}

The file is not transferred and then FileUploadSelector continues with never-ending requesting AsyncMonitor.

Firefox, Edge, IE, Opera without a problem!

Could you pls give me an advise where I should looking for a problem?

**Comment by bentolor** [comment]
I have not installation handy to try on my own: Could you try to compare the communication in the developer tools between Chrome & Firefox. 

In both browsers they're accessible on F12. 

I'd look out for:

- Console: Are there any client-side errors or warnings?
- Requests: How do they differ?

**Comment by radekcz** [comment]
Yes, we have tried compare the communication between Chrome and FF:

In Chrome there is missing (main) POST request with the file which is in FF:

    POST ?sid=echopoint.tucana.UploadProgressService&i=C.3109&x=3clunmk42z0ozk

but next GET requests are in both:
    
    GET ?sid=echopoint.tucana.UploadProgressService&i=C.3109&x=3clunmk42z0ozk

So, in Chrome there starts no file transfer...

**Comment by bentolor** [comment]
If the requests are equal this seems to indicate a client-side error which should be somehow visible in the console as warning etc.

The chrome release notes https://chromereleases.googleblog.com/2019/12/stable-channel-update-for-desktop.html  mention things like:

 [$10000][944619] High CVE-2019-13727: Insufficient policy enforcement in WebSockets. Reported by @piochu on 2019-03-21
 [$N/A][1004212] Low CVE-2019-13762: Insufficient policy enforcement in downloads. Reported by csanuragjain (@csanuragjain) on 2019-09-16

Maybe the culprit lies in there?

I won't be able too look onto this issue before 2020. Please feel free to ping me then again if there was no progress in this matter.

**Comment by radekcz** [comment]
Thank Benjamin for your hints!

In Chrome there is missing POST request with file, so I think that is the main problem. But the console (all levels) is clear - no warnings, no errors (verbose mode).

It seems the form is incorrectly sent, any idea?

**Comment by radekcz** [comment]
#3

**Comment by bentolor** [comment]
Thanks for you awesome contribution! Really simple fix. Glad you were able to sort it out.

As mentioned in the merge request: I merged it right away. But do you need a new upstream release in Maven central?

**Comment by radekcz** [comment]
Thank @bentolor for the merge. No, I don't need a new upstream release now. I've already made the release for us.
